- name: Create vim autoload directory
  file:
    path: "/home/{{ user }}/.vim/autoload"
    state: directory
    mode: '0755'

- name: Download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ user }}/.vim/autoload/plug.vim"
    mode: '0755'

- name: Install nvim-pip
  shell: python3 -m pip install --user --upgrade pynvim

- name: Install vim plugins
  shell: nvim --headless +PlugInstall +GoInstallBinaries +qall
