icons_format = "{icon}"

[theme]
theme = "ctp-macchiato"
[theme.overrides]
idle_bg = "#2a2f38"
idle_fg = "#f1fffa"

[icons]
icons = "awesome6"

[[block]]
block = "bluetooth"
mac = "14:28:76:96:EE:06"
disconnected_format = ""
format = " $icon $name{ $percentage|} "
[[block]]
block = "bluetooth"
mac = "94:DB:56:16:FD:0F"
disconnected_format = ""
format = " $icon $name{ $percentage|} "
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"

[[block]]
block = "battery"
format = " $icon $percentage $power"
full_format = ""

[[block]]
block = "cpu"
interval = 1
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 1
format = "$icon $timestamp.datetime(f:'%A-%B %Y-%m-%d %H:%M:%S')"
