- name: Craete directories
  file:
    path: "/home/{{ user }}/{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ base_config_directories }}"

- name: Link vim directories
  file:
    src: "{{ playbook_dir}}/../vim/{{ item }}"
    dest: "/home/{{ user }}/.vim/{{ item }}"
    state: link
  loop: "{{ vim_directories }}"

- name: Remove conflicting configs if present
  file:
    path: "/home/{{ user }}/{{ item }}"
    state: absent
  loop: "{{ conflicting_configurations_to_remove }}"

- name: Link root configs
  file:
    src: "{{ playbook_dir }}/../{{ item }}"
    dest: "/home/{{ user }}/{{ item }}"
    state: link
  loop: "{{ root_configurations }}"

- name: Link app configs
  file:
    src: "{{ playbook_dir }}/../.config/{{ item }}"
    dest: "/home/{{ user }}/.config/{{ item }}"
    state: link
  loop: "{{ app_configurations }}"
