- name: Craete directories
  file:
    path: "/home/{{ user }}/{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ base_config_directories }}"

- name: Link vim directories
  file:
    src: "{{ playbook_dir}}/../vim/{{ item }}"
    dest: "/home/{{ user }}/.vim/{{ item }}"
    state: link
  loop: "{{ vim_directories }}"

- name: Remove conflicting configs if present
  file:
    path: "/home/{{ user }}/{{ item }}"
    state: absent
  loop: "{{ conflicting_configurations_to_remove }}"

- name: Link root configs
  file:
    src: "{{ playbook_dir }}/../{{ item }}"
    dest: "/home/{{ user }}/{{ item }}"
    state: link
  loop: "{{ root_configurations }}"

- name: Create app configuration directories
  file:
    path: "/home/{{ user }}/.config/{{ item.app }}"
    state: directory
  loop: "{{ app_configs }}"

- name: Copy app confiurations
  template:
    src: "{{ item.0.app }}/{{ item.1 }}.j2"
    dest: "/home/{{ user }}/.config/{{ item.0.app }}/{{ item.1 }}"
  with_subelements:
    - "{{ app_configs }}"
    - configs

- name: Restart apps
  shell: "{{ item }}"
  loop: "{{ restart_apps }}"
