---
  - name: "Symlink configs"
    hosts: localhost
    connection: local
    become: no
    tasks:
      - name: Craete directories
        file:
          path: "/home/erre/{{ item }}"
          state: directory
          mode: '0755'
        loop:
          - .vim
          - .config

      - name: Link vim directories
        file:
          src: "{{ playbook_dir}}/../vim/{{ item }}"
          dest: "/home/erre/.vim/{{ item }}"
          state: link
        loop:
          - plugin
          - ftplugin
          - after

      - name: Remove conflicting configs if present
        file:
          path: "/home/erre/{{ item }}"
          state: absent
        loop:
          - .gitconfig
          - .zshrc

      - name: Link root configs
        file:
          src: "{{ playbook_dir}}/../{{ item }}"
          dest: "/home/erre/{{ item }}"
          state: link
        loop:
          - .gitconfig
          - .gitignore_global
          - .tmux.conf
          - .vimrc
          - .zshrc
          - .fonts

      - name: Link app configs
        file:
          src: "{{ playbook_dir}}/../.config/{{ item }}"
          dest: "/home/erre/.config/{{ item }}"
          state: link
        loop:
          - alacritty
          - nvim
          - rofi
