---
  - name: "Install docker"
    hosts: localhost
    connection: local 
    become: yes
    tasks:
      - name: Install docker
        community.general.pacman:
          name:
            - docker

      - name: Start docker service
        ansible.builtin.systemd:
          state: started
          name: docker.service

      - name: Add user to docker group
        user:
          name: erre
          groups: docker
          append: yes
