---
  - name: "Install and it's plugin manager"
    hosts: localhost
    connection: local 
    become: no
    tasks:
      - name: Install tmux
        become: yes
        pacman:
          name:
            - tmux

      - name: Install tmux plugin manager
        git:
          repo: https://github.com/tmux-plugins/tpm.git
          dest: /home/erre/.tmux/plugins/tpm

      - name: Install tmux plugin manager
        shell: /home/erre/.tmux/plugins/tpm/bin/install_plugins
