---
  - name: "Install various tools"
    hosts: localhost
    connection: local
    become: true
    tasks:
      - name: Install tools
        community.general.pacman:
          name:
            - alacritty
            - autorandr
            - brave-browser # TODO: Add sync if possible
            - gcc
            - ctop
            - curl
            - fd
            - fzf
            - go
            - neovim
            - pass
            - python-pip
            - ripgrep
            - rofi
            - zathura
