---
  - name: "Install various tools"
    hosts: localhost
    connection: local 
    become: no
    tasks:
      - name: Install zsh
        community.general.pacman:
          name:
            - zsh

      - name: Change default shell to zsh
        user:
          name: erre # TODO: make this dynamic
          shell: /bin/zsh

      - name: Check if ozsh is already installed
        stat:
          path: ~/.oh-my-zsh
        register: ozsh_stat

      - name: Download zsh installer
        get_url:
          url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
          dest: /tmp/zsh-installer.sh
          mode: '0700'
        when: not ozsh_stat.stat.exists

      - name: Execute the zsh-installer.sh
        shell: /tmp/zsh-installer.sh
        when: not ozsh_stat.stat.exists

      - name: Remove the zsh-installer.sh
        file:
          path: /tmp/zsh-installer.sh
          state: absent
        when: not ozsh_stat.stat.exists
